name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow  # Install MLflow

      # DVC: Create credentials.json
      - name: Create credentials.json
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo $GDRIVE_CREDENTIALS_DATA > credentials.json

      - name: Modify DVC Remote
        run: |
          uv run dvc remote modify --local gdrive-remote gdrive_service_account_json_file_path credentials.json

      - name: DVC Pull Data
        run: |
          uv run dvc pull -v

      # Run CNN Inference
      - name: Run tests
        run: |
          mkdir -p /home/runner/work/classification-pytorch/classification-pytorch/plots
          python3 main.py --mode test --data_path ./data/test/ --model_path ./models/cnn_resnet18_freeze_backbone_False.pth

      # Train CNN Model with MLflow
      - name: Train CNN with MLflow
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}  # Using the MLflow tracking URI from secrets
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}"

          # Set up directories for saving models and plots
          mkdir -p /home/runner/work/classification-pytorch/classification-pytorch/plots

          # Start the MLflow experiment and track parameters
          python3 train.py --data_path ./data/train/ --epochs 50 --learning_rate 0.001 --model_dir ./models --plot_dir ./plots --mlflow

    # Log the plots or any other artifacts
    mlflow.log_artifact('./plots')  # Log the plot folder for metrics visualizations
          "
